"""
Django settings for core_project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Se lee del entorno (.env en local). Nunca la escribas en este archivo.
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-only-insecure-cambiar-en-produccion')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').strip().lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]').split(',')
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# El TLS lo termina el nginx del host y Django solo ve HTTP en clear, asi que
# sin esto request.is_secure() es False: build_absolute_uri() genera enlaces
# http:// y la comprobacion de Referer de CSRF se omite.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Terceros
    'corsheaders',
    # Apps propias
    'usuarios',
    'courses',
    'evaluaciones',
    'foro',
]

MIDDLEWARE = [
    # CorsMiddleware debe ir ANTES de CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve /static/ y /media/ detrás de gunicorn
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ── CORS ──────────────────────────────────────
# El frontend llama siempre a rutas relativas (/api/...), nunca a un host
# absoluto, asi que el navegador no cruza origenes: nginx (produccion) y Vite
# (desarrollo) sirven el API en el mismo origen que la SPA. CORS queda cerrado
# y solo se abre si CORS_ALLOWED_ORIGINS lista dominios en el .env; con la
# lista vacia no se permite ninguno. Antes esto valia True y aceptaba
# cualquier origen.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]

# ── Firebase ────────────────────────────────────
# El projectId contra el que se audita el ID token que manda el navegador. Es
# el `projectId` de frontend/src/config/firebase.js: si los dos no coinciden,
# verify_oauth2_token rechaza todos los tokens y nadie puede entrar.
#
# Sin valor por defecto a proposito, igual que EMAIL_HOST_PASSWORD: si la
# variable no esta, el decorador de usuarios.permisos responde 503 con un
# mensaje de configuracion, no un 401 que cerraria la sesion de todos los
# estudiantes. No es un secreto (esta en el bundle del navegador), pero tiene
# que estar en el entorno porque cambiar de proyecto no se nota hasta que deja
# de funcionar el login.
FIREBASE_PROJECT_ID = os.environ.get('FIREBASE_PROJECT_ID', '').strip()

ROOT_URLCONF = 'core_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Debe llevar slash inicial: sin él el navegador resuelve 'static/...'
# relativo a la URL actual y el admin pide /admin/static/... (404).
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise: sirve estáticos comprimidos y además los /media/ subidos
# (los certificados PDF), que Django no sirve solo en modo runserver.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
# OJO: no se usa WHITENOISE_ROOT. El middleware de whitenoise para Django
# ignora WHITENOISE_PREFIX y sirve ese directorio en la raiz de la URL, no
# bajo /media/. Los archivos subidos los sirve nginx con un alias.

# Email Settings (Configurar para Produccion)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# Sin fallback a proposito: si el .env no cargo, EMAIL_HOST_PASSWORD queda vacio y
# el envio falla con 500 opaco en vez de un error de configuracion claro.
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
# Corta el envio si el SMTP se queda colgado: el aviso de aprobacion se dispara
# dentro del request y no debe retener la peticion del quiz.
EMAIL_TIMEOUT = 10

# A quien se avisa por correo. CSV en el entorno, ej.
# NOTIF_DESTINATARIOS=marketingmagas2026@gmail.com,otro@dominio.com
# Sirve tanto para el aviso de aprobacion como para el certificado.
NOTIF_DESTINATARIOS = [
    correo.strip()
    for correo in os.environ.get('NOTIF_DESTINATARIOS', '').split(',')
    if correo.strip()
]


