# Etapa 1: Construcción (¡Actualizado a Node 20!)
FROM node:20-alpine AS build
WORKDIR /app

# Entramos a tu carpeta frontend a buscar los paquetes
COPY frontend/package*.json ./
RUN npm install

# Copiamos todo el código de React
COPY frontend/ ./
RUN npm run build

# ... (tu código de construcción de Node arriba)

FROM nginx:alpine
# Copiamos los archivos de React compilados
# Cámbialo para que quede así (fíjate en la última palabra):
COPY --from=build /app/dist /usr/share/nginx/html/rutainduccion

# ESTA ES LA LÍNEA MÁGICA: Reemplaza el archivo por defecto con el tuyo
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
