# Generated by Django 6.1.1 on 2026-09-30 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_course_accent_color_course_badge_course_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('puntaje_aprobacion', models.PositiveSmallIntegerField(default=90, verbose_name='Puntaje de aprobación (%)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Pregunta')),
                ('contexto', models.TextField(blank=True, default='', verbose_name='Contexto')),
                ('es_larga', models.BooleanField(default=False, verbose_name='Texto largo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluaciones.evaluacion', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Opción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='Correcta')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='evaluaciones.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
