# Generated by Django 6.0.5 on 2026-07-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user_id', 'course_id', 'lesson_id')},
        ),
    ]
