# Generated by Django 6.0.5 on 2026-07-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_userprogress_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ID de Usuario')),
                ('course_id', models.CharField(max_length=255, verbose_name='ID de Curso')),
                ('course_name', models.CharField(max_length=255, verbose_name='Nombre del Curso')),
                ('score', models.IntegerField(default=0, verbose_name='Puntaje')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total Preguntas')),
                ('percentage', models.IntegerField(default=0, verbose_name='Porcentaje')),
                ('passed', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'unique_together': {('user_id', 'course_id')},
            },
        ),
    ]
