# Generated by Django 6.1.1 on 2026-09-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_calificacion_identidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ID de Usuario')),
                ('user_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre del Usuario')),
                ('user_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo del Usuario')),
                ('course_id', models.CharField(max_length=255, verbose_name='ID de Curso')),
                ('course_name', models.CharField(max_length=255, verbose_name='Nombre del Curso')),
                ('archivo', models.CharField(max_length=500, verbose_name='Archivo')),
                ('notificado', models.BooleanField(default=False, verbose_name='Notificado')),
                ('notificacion_error', models.TextField(blank=True, default='', verbose_name='Error de notificación')),
                ('intentos', models.PositiveIntegerField(default=0, verbose_name='Intentos de envío')),
                ('fecha_emision', models.DateTimeField(auto_now=True, verbose_name='Fecha de emisión')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-fecha_emision'],
                'unique_together': {('user_id', 'course_id')},
            },
        ),
    ]
