# Generated by Django 6.1.1 on 2026-09-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='accent_color',
            field=models.CharField(default='bg-[#f6811e]', max_length=50, verbose_name='Color (clase Tailwind)'),
        ),
        migrations.AddField(
            model_name='course',
            name='badge',
            field=models.CharField(default='Nuevo', max_length=50, verbose_name='Etiqueta'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='1h', max_length=50, verbose_name='Duración total'),
        ),
        migrations.AddField(
            model_name='course',
            name='icon_type',
            field=models.CharField(choices=[('Bot', 'Bot'), ('Users', 'Users'), ('Megaphone', 'Megaphone'), ('LineChart', 'LineChart')], default='Bot', max_length=50, verbose_name='Icono'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='Básico', max_length=50, verbose_name='Nivel'),
        ),
    ]
