# Generated by Django 6.1.1 on 2026-10-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_calificacion_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='token',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
    ]
