# Generated by Django 6.1.1 on 2026-10-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_backfill_certificado_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del recurso')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('Imagen', 'Imagen')], max_length=10, verbose_name='Tipo')),
                ('archivo', models.FileField(upload_to='recursos/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['order'],
            },
        ),
    ]
